version: '3.4'

services:
  catalog:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5003:80"

  frontend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ApiConfigs__EventCatalog__Uri=http://catalog
      - ApiConfigs__Ordering__Uri=http://ordering
    ports:
      - "5001:80"
      - "5002:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  ordering:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5004:80"

  maildev:
    container_name: "smtpserver"
    image: "maildev/maildev:2.1.0" # https://hub.docker.com/r/maildev/maildev
    ports:
      - "1025:1025"
      - "1080:1080"
    networks:
      - globoticket           