apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: daprworkshop-redis-master:6379
  - name: redisPassword
    value: JFtSf5XHuv # Change this password